apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ham-application-assembler
rules:
- apiGroups:
  - "*"
  resources:
    - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch