apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "wordpress-01"
  namespace: default
  labels:
    app.kubernetes.io/name: "wordpress-01"
  annotations:
    tools.hybridapp.io/hybrid-discover: "enabled"
    #tools.hybridapp.io/hybrid-discover-create-assembler: "enabled"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "wordpress-01"
  componentKinds:
    - group: v1
      kind: Service
    - group: apps
      kind: StatefulSet
  addOwnerRef: false
