name: Docker Image CI

on:
  push:
    branches: [ "shadman-0916" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -f build/Dockerfile --tag sophiaxu0424/ham-application-assembler:test
